---
- name: Set and Update Private Ip's within website
  hosts: localhost
  tasks:
    - name: Load Terraform output
      command: cat ../terraform_outputs.json
      register: terraform_outputs
      delegate_to: localhost
      become: false

    - name: Set backend and DB private IPs
      set_fact:
        backend_server_private_ip: "{{ terraform_outputs.stdout | from_json | json_query('backend_server_private_ip.value') }}"
        db_server_private_ip: "{{ terraform_outputs.stdout | from_json | json_query('db_server_private_ip.value') }}"

    - name: Print the backend and database IPs
      debug:
        msg:
          - "Backend Private IP: {{ backend_server_private_ip }}"
          - "Database Private IP: {{ db_server_private_ip }}"

    - name: Update api.js with backend IP
      lineinfile:
        path: ../client/src/config/api.js
        regexp: '  baseURL: "http://.*:5000/api",'
        line: '  baseURL: "http://{{ backend_server_private_ip }}:5000/api",'

    - name: Update api.js with backend IP
      lineinfile:
        path: ../client/src/config/api.js
        regexp: 'export const apiUrl = "http://.*:5000/api"'
        line: 'export const apiUrl = "http://{{ backend_server_private_ip }}:5000/api"'

    - name: Update .env with database IP
      lineinfile:
        path: ../server/.env
        regexp: 'DB_URL=.*'
        line: 'DB_URL=mongodb://{{ db_server_private_ip }}:27017/walid-library'

    - name: Stage changes for Git
      command: git add ../client/src/config/api.js ../server/.env ../terraform_outputs.json

    - name: Commit changes
      command: git commit -m "Update API and DB IPs in configuration files"

    - name: Push changes to GitHub
      command: git push origin main

